### ISSUE TITLE
lexical.h implement more functionality

### ISSUE THREAD

**Issue by ajjl** [ajjl/compiler#11]
lexical.c:194:          /* =BUG= must call either string_accept() or _reject() */
lexical.c:195:          /* =BUG= lex_next.value must be must be set to something */

**Comment by ajjl** [comment]
Prof Jones marked as a bug

**Comment by bradziolko** [comment]
I have been looking at a lot of the code, and it would appear that the string_accept() and string_reject() is handled by symboltable.c, lines 54 and 59 respectively.  The comments on string_accept() and _reject() in the header stringpool.h say these should be decided by the symboltable.  SO, I think that bug is done, but wasn't sure if I was missing something so it'd be nice if someone else confirmed.

**Comment by bradziolko** [comment]
I believe this can be closed.  lex.next_value is being set by symbol_lookup().  Removed these two bugs.

**Comment by ajjl** [comment]
Thanks! closed by # d97c286
